# @package _global_
defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/launcher: joblib

name: "food_classifier_mobilenetv3_hparam"
experiment_name: "food_classifier_mobilenetv3_hparam"
optimization_metrics: "test/acc_best"

hydra:
  mode: "MULTIRUN"
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 123
      n_startup_trials: 4
    direction: maximize
    study_name: food_mobilenetv3_hparam_optimization
    storage: null
    n_trials: 10
    n_jobs: 4
    params:
      model.base_model: choice("mobilenetv3_large_100", "mobilenetv3_small_100")
      model.num_classes: 101  # Food-101 dataset
      model.pretrained: True
      model.learning_rate: choice(5e-5, 1e-4, 3e-4)
      model.weight_decay: choice(1e-5, 5e-5, 1e-4)
      # model.dropout_rate: choice(0.2, 0.3)
      model.factor: choice(0.2, 0.3)
      data.batch_size: choice(32, 64)
      regularization.gradient_clipping: choice(0.5, 1.0)
      trainer.max_epochs: 10

  launcher:
    n_jobs: 4
    backend: 'loky'

data:
  batch_size: 32
  image_size: 224

trainer:
  min_epochs: 5
  max_epochs: 10
