# @package _global_
defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/launcher: joblib

name: "fruit_veg_classifier_resnet18_hparam"
experiment_name: "fruit_veg_classifier_resnet18_hparam"
optimization_metrics: "test/acc_best"

hydra:
  mode: "MULTIRUN"
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 123
      n_startup_trials: 4
    direction: maximize
    study_name: fruit_veg_resnet18_hparam_optimization
    storage: null
    n_trials: 2
    n_jobs: 4 
    params:
      model.base_model: choice("resnet18")
      model.num_classes: 37  # Adjusted for fruit and vegetable classification
      model.pretrained: choice(True, False)
      model.learning_rate: choice(1e-4, 5e-4, 1e-3, 3e-3, 1e-2)

  launcher:
    n_jobs: 3
    backend: 'loky'

data:
  batch_size: 32

trainer:
  min_epochs: 1
  max_epochs: 1
