# @package _global_
defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/launcher: joblib

name: "food_classifier_vit_tiny_hparam"
experiment_name: "food_classifier_vit_tiny_hparam"
optimization_metrics: "test/acc_best"

hydra:
  mode: "MULTIRUN"
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 123
      n_startup_trials: 4
    direction: maximize
    study_name: food_vit_tiny_hparam_optimization
    storage: null
    n_trials: 15
    n_jobs: 6
    params:
      model.base_model: choice("vit_tiny_patch16_224", "vit_small_patch16_224")
      model.num_classes: 101  # Food-101 dataset
      model.pretrained: True
      model.patch_size: choice(16)
      model.embed_dim: choice(128, 192)
      model.depth: choice(12)
      model.num_heads: choice(4, 8)
      model.mlp_ratio: choice(3, 4)
      model.learning_rate: choice(5e-5, 1e-4, 3e-4)
      model.weight_decay: choice(1e-5, 5e-5, 1e-4)
      model.dropout_rate: choice(0.1, 0.2)
      data.batch_size: choice(16, 32, 64)
      trainer.max_epochs: 10

  launcher:
    n_jobs: 6
    backend: 'loky'

data:
  batch_size: 32
  image_size: 224

trainer:
  min_epochs: 5
  max_epochs: 10
